/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author ANTONIO-LIBORIO
 */
public class frmInicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public frmInicio() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        editMenu = new javax.swing.JMenu();
        btnTipoUsuario = new javax.swing.JMenuItem();
        btnMetodoDePago = new javax.swing.JMenuItem();
        btnPlanUsuario = new javax.swing.JMenuItem();
        btnTipoDenuncia = new javax.swing.JMenuItem();
        btnProtocolo = new javax.swing.JMenuItem();
        btnRestablecerContraseña = new javax.swing.JMenu();
        btnUsuarios = new javax.swing.JMenuItem();
        btnRestablecerPassword = new javax.swing.JMenuItem();
        fileMenu = new javax.swing.JMenu();
        btnDenuncias = new javax.swing.JMenuItem();
        btnRespaldowadwa = new javax.swing.JMenu();
        btnRespaldo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        escritorio.setForeground(new java.awt.Color(0, 204, 204));

        editMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/carpeta.png"))); // NOI18N
        editMenu.setMnemonic('e');
        editMenu.setText("Datos");

        btnTipoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuario.png"))); // NOI18N
        btnTipoUsuario.setMnemonic('t');
        btnTipoUsuario.setText("Tipo Usuario");
        editMenu.add(btnTipoUsuario);

        btnMetodoDePago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pagar.png"))); // NOI18N
        btnMetodoDePago.setMnemonic('y');
        btnMetodoDePago.setText("Metodo de Pago");
        editMenu.add(btnMetodoDePago);

        btnPlanUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/las-tendencias-del-mercado.png"))); // NOI18N
        btnPlanUsuario.setMnemonic('p');
        btnPlanUsuario.setText("Plan de Usuario");
        editMenu.add(btnPlanUsuario);

        btnTipoDenuncia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/hoja.png"))); // NOI18N
        btnTipoDenuncia.setText("Tipo de denuncia");
        btnTipoDenuncia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTipoDenunciaActionPerformed(evt);
            }
        });
        editMenu.add(btnTipoDenuncia);

        btnProtocolo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ciencias-politicas.png"))); // NOI18N
        btnProtocolo.setText("Protocolos");
        editMenu.add(btnProtocolo);

        menuBar.add(editMenu);

        btnRestablecerContraseña.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/carpeta.png"))); // NOI18N
        btnRestablecerContraseña.setMnemonic('h');
        btnRestablecerContraseña.setText("Administración");

        btnUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cliente.png"))); // NOI18N
        btnUsuarios.setMnemonic('c');
        btnUsuarios.setText("Usuarios");
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });
        btnRestablecerContraseña.add(btnUsuarios);

        btnRestablecerPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/correo.png"))); // NOI18N
        btnRestablecerPassword.setMnemonic('a');
        btnRestablecerPassword.setText("Recuperar Contraseña");
        btnRestablecerContraseña.add(btnRestablecerPassword);

        menuBar.add(btnRestablecerContraseña);

        fileMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/carpeta.png"))); // NOI18N
        fileMenu.setMnemonic('f');
        fileMenu.setText("Operativo");

        btnDenuncias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/problema.png"))); // NOI18N
        btnDenuncias.setMnemonic('o');
        btnDenuncias.setText("Denuncias");
        fileMenu.add(btnDenuncias);

        menuBar.add(fileMenu);

        btnRespaldowadwa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/seo-y-web.png"))); // NOI18N
        btnRespaldowadwa.setText("Respaldo");

        btnRespaldo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/seo-y-web.png"))); // NOI18N
        btnRespaldo.setText("Respaldo");
        btnRespaldowadwa.add(btnRespaldo);

        menuBar.add(btnRespaldowadwa);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnTipoDenunciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTipoDenunciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTipoDenunciaActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuItem btnDenuncias;
    public javax.swing.JMenuItem btnMetodoDePago;
    public javax.swing.JMenuItem btnPlanUsuario;
    public javax.swing.JMenuItem btnProtocolo;
    public javax.swing.JMenuItem btnRespaldo;
    public javax.swing.JMenu btnRespaldowadwa;
    public javax.swing.JMenu btnRestablecerContraseña;
    public javax.swing.JMenuItem btnRestablecerPassword;
    public javax.swing.JMenuItem btnTipoDenuncia;
    public javax.swing.JMenuItem btnTipoUsuario;
    public javax.swing.JMenuItem btnUsuarios;
    public javax.swing.JMenu editMenu;
    public javax.swing.JDesktopPane escritorio;
    public javax.swing.JMenu fileMenu;
    public javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
